global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Graph;
global using Sequence.Core.Internal;
global using Sequence.Core;
global using Sequence.Core.Attributes;
global using Sequence.Core.Internal.Errors;
global using Sequence.Core.Util;
global using Entity = Sequence.Core.Entity;
global using System;
global using Azure.Core;
global using Azure.Identity;
global using CSharpFunctionalExtensions;
global using Sequence.Core.Entities.Schema;
