include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.linux.yml

variables:
  PUBLISH_CONNECTOR: 1
  PUBLISH_NUGETORG: 1
  


test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG -v normal
      --filter "Category!=Integration&Category!=IntegrationShort"
      --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory ./