include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.linux.yml

variables:
  PUBLISH_CONNECTOR: 1
  PUBLISH_NUGETORG: 1
  
.fix_coverage:
- &fix_coverage |
$report = Get-Content -Path "*/coverage.cobertura.xml" -Raw
$fixPaths = $report -replace "filename=`".+?${env:CI_PROJECT_NAME}(/|\\)", "filename=`""
$fixPaths = $fixPaths -replace '\\', '/'
$outPath = Join-Path (Get-Location) "coverage.$($env:CI_JOB_NAME -replace "[^\w]+", "-").xml"
[System.IO.File]::WriteAllText($outPath, $fixPaths)


test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG -v normal
      --filter "Category!=Integration&Category!=IntegrationShort"
      --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory ./
    - *fix_coverage