include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.linux.yml

variables:
  PUBLISH_CONNECTOR: 1
  PUBLISH_NUGETORG: 1

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG -v normal --filter "Category!=Integration"
      --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory ./
    - >-
      pwsh -Command '$report = Get-Content -Path "*/coverage.cobertura.xml" -Raw ;
      $fixPaths = $report -replace "filename=`".+?${env:CI_PROJECT_NAME}(/|\\)", "filename=`"" ;
      [System.IO.File]::WriteAllText("./coverage.$($env:CI_JOB_NAME -replace "[^\w]+", "-").xml", $fixPaths)'

# Skipping mutation testing as Stryker currently doesn't support filters
mutation testing:
  rules:
    - when: never
